### PR TITLE
#30 `EOCommenter` tests fix for IDEA 2021

### PR DESCRIPTION
**Pull request by maxonfjvipon**
Closes: #30

---

## PR-Codex overview
This PR focuses on updating the Java version to 17 and making various code changes and improvements. 

### Detailed summary
- Updated Java version from 14 to 17 in multiple files and workflows.
- Renamed test classes `EoParsingTestComments` and `EoParsingTest1` to `EoParsingCommentsTest` and `EoParsingTest`, respectively.
- Added `@SuppressWarnings("PMD.JUnit5TestShouldBePackagePrivate")` annotation to `EoCommenterTest` and `EoParsingCommentsTest`.
- Updated `ideaVersion` in `gradle.properties` to `2021.1`.
- Updated `antlr4Version` in `gradle.properties` to `4.13.0`.
- Updated `pluginVersion` in `gradle.properties` to `0.0.0`.
- Updated `org.jetbrains.intellij` plugin version in `build.gradle` to `1.14.2`.
- Updated `languageVersion` in `build.gradle` to `JavaLanguageVersion.of(17)`.
- Updated `gradleVersion` in `build.gradle` to `7.4.2`.
- Updated `junit` version in `build.gradle` to `4.13.2`.

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by maxonfjvipon** [comment]
@yegor256 could you please decrease code coverage level on this project to merge the pull request? I added `todo` to enable some tests and increase code coverage level back in the future

**Comment by yegor256** [comment]
@maxonfjvipon you can decrease it yourself, just make a new separate PR. We will merge it (manually, without Rultor) and then will merge this one.

**Comment by maxonfjvipon** [comment]
@yegor256 please have a look

**Comment by yegor256** [comment]
@rultor merge

**Comment by maxonfjvipon** [comment]
@yegor256 Does Rultor take `.rultor.yml` from RP or from `master` branch?

**Comment by yegor256** [comment]
@maxonfjvipon only from `master`. If you want to modify it, you should make another PR first

**Comment by maxonfjvipon** [comment]
@yegor256 please try to merge again

**Pull request merged**
