### PR TITLE
Added hot key for commenting

### PR DESCRIPTION
**Pull request by yasamprom**
objectionary/eo-intellij-plugin#17
Now code commenting is possible by selecting block and pressing `control + /` on linux/windows or `command + /` on mac os. Same combinations for uncommenting.

### CODE REVIEW

**Comment by yasamprom** [comment]
@yegor256 please check

**Comment by yegor256** [comment]
@rultor merge

**Comment by yasamprom** [comment]
@yegor256 shall we release `0.0.3` version?

**Comment by yegor256** [comment]
@rultor release, tag is `0.0.3`

**Pull request merged**
