### PR TITLE
Build depends on qulice

### PR DESCRIPTION
**Pull request by yasamprom**
objectionary/eo-intellij-plugin#22

### CODE REVIEW

**Comment by yasamprom** [comment]
@yegor256 please merge

**Comment by yegor256** [comment]
@rultor merge

**Comment by yasamprom** [comment]
@yegor256 I forgot to add merge section in `.rultor.yml`. Let's try one more time

**Comment by yegor256** [comment]
@yasamprom it won't work like this. `.rultor.yml` is used from master, not from your branch

**Comment by yegor256** [comment]
@yasamprom I updated `.rultor.yml` in master: 78b056b

**Comment by yasamprom** [comment]
@yegor256 check please

**Comment by yegor256** [comment]
@yasamprom pushed to master

**Comment by yasamprom** [comment]
@yegor256 ready to merge

**Comment by yasamprom** [comment]
@yegor256

**Comment by yegor256** [comment]
@rultor merge

**Pull request merged**
